export const cryptoList = [
  {
    name: 'Bitcoin',
    symbolBig: 'BTC',
    symbolSmall: 'btc',
    img: require('../assets/images/btc.png'),
  },
  {
    name: 'Etherium',
    symbolBig: 'ETH',
    symbolSmall: 'eth',
    img: require('../assets/images/eth.png'),
  },
  {
    name: 'Litecoin',
    symbolBig: 'LTC',
    symbolSmall: 'ltc',
    img: require('../assets/images/ltc.png'),
  },
  {
    name: 'Ripple',
    symbolBig: 'XRP',
    symbolSmall: 'xrp',
    img: require('../assets/images/xrp.png'),
  },
  {
    name: 'Quantum',
    symbolBig: 'QTUM',
    symbolSmall: 'qtum',
    img: require('../assets/images/qtum.png'),
  },
  {
    name: 'Neo',
    symbolBig: 'NEO',
    symbolSmall: 'neo',
    img: require('../assets/images/neo.png'),
  },
  {
    name: 'Stellar',
    symbolBig: 'XLM',
    symbolSmall: 'xlm',
    img: require('../assets/images/xlm.png'),
  },
  {
    name: 'Bitcoin Cash',
    symbolBig: 'BCH',
    symbolSmall: 'bch',
    img: require('../assets/images/bch.png'),
  },
  {
    name: 'Etherium Classic',
    symbolBig: 'ETC',
    symbolSmall: 'etc',
    img: require('../assets/images/etc.png'),
  },
  {
    name: 'Cardano',
    symbolBig: 'ADA',
    symbolSmall: 'ada',
    img: require('../assets/images/ada.png'),
  },
  {
    name: 'EOS',
    symbolBig: 'EOS',
    symbolSmall: 'eos',
    img: require('../assets/images/eos.png'),
  },
  {
    name: 'NEM',
    symbolBig: 'XEM',
    symbolSmall: 'xem',
    img: require('../assets/images/xem.png'),
  },
  {
    name: 'Monero',
    symbolBig: 'XMR',
    symbolSmall: 'xmr',
    img: require('../assets/images/xmr.png'),
  },
  {
    name: 'Dash',
    symbolBig: 'DASH',
    symbolSmall: 'dash',
    img: require('../assets/images/dash.png'),
  },
];
